pipeline {
    agent any

    environment {
        JAVA_HOME = '/opt/java/openjdk'
        PATH = "${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${env.PATH}"
        MAVEN_HOME = '/opt/maven'
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Verify Java & Maven') {
            steps {
                sh 'echo "JAVA VERSION:" && java -version'
                sh 'echo "MAVEN VERSION:" && mvn -version'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('Complete') {
            steps {
                echo '✅ Job Complete!'
            }
        }
    }
}
